# Google Cloud Build configuration for TriSynq AI Website
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/trisynq-website:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/trisynq-website:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/trisynq-website:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/trisynq-website:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'trisynq-website'
      - '--image'
      - 'gcr.io/$PROJECT_ID/trisynq-website:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production,NEXT_TELEMETRY_DISABLED=1'
      - '--set-secrets'
      - 'XYNERGY_API_KEY=xynergy-api-key:latest,NEXT_PUBLIC_GA_MEASUREMENT_ID=ga-measurement-id:latest'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/trisynq-website:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/trisynq-website:latest'

# Build configuration
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
