# Google Cloud Build configuration for ClearForge Website
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/clearforge-website:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/clearforge-website:latest'
      - '.'

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/clearforge-website:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/clearforge-website:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'clearforge-website'
      - '--image'
      - 'gcr.io/$PROJECT_ID/clearforge-website:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--port'
      - '3000'
      - '--set-env-vars'
      - 'NODE_ENV=production,NEXT_PUBLIC_ENVIRONMENT=production,NEXT_TELEMETRY_DISABLED=1'
      - '--set-secrets'
      - 'GATEWAY_API_KEY=gateway-api-key:latest,NEXT_PUBLIC_GATEWAY_URL=gateway-url:latest,NEXT_PUBLIC_GA_MEASUREMENT_ID=ga-measurement-id:latest'

images:
  - 'gcr.io/$PROJECT_ID/clearforge-website:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/clearforge-website:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'

timeout: '1200s'
