# Google Cloud Build configuration for TriSynq AI website
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/trisynq-website:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/trisynq-website:latest'
      - '.'
    timeout: '600s'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/trisynq-website:$BUILD_ID'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/trisynq-website:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'trisynq-website'
      - '--image'
      - 'gcr.io/$PROJECT_ID/trisynq-website:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '1'
      - '--port'
      - '3000'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--service-account'
      - 'trisynq-website@$PROJECT_ID.iam.gserviceaccount.com'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/trisynq-website:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/trisynq-website:latest'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100

# Timeout for the entire build
timeout: '1200s'