import { Metadata } from 'next';
import Section from '@/components/ui/Section';
import Card from '@/components/ui/Card';
import Button from '@/components/ui/Button';
import { generateMetadata } from '@/components/seo/SEOHead';

export const metadata: Metadata = generateMetadata({
  title: 'Our Story - From Enterprise to Accessible',
  description: 'How we started and why we are building ClearForge. The founder journey from enterprise systems to small business accessibility.',
});

export default function OurStoryPage() {
  return (
    <>
      <Section background="gradient" className="pt-32 pb-20">
        <div className="max-w-4xl mx-auto text-center">
          <h1 className="text-5xl md:text-6xl font-bold mb-6">
            Our Story
          </h1>
          <p className="text-2xl text-gray-300">
            From building billion-dollar enterprise systems to making them accessible for everyone.
          </p>
        </div>
      </Section>

      <Section background="dark">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-4xl font-bold mb-8">How We Started</h2>

          <div className="space-y-6 text-lg text-gray-300">
            <p>
              For 20+ years, we built the systems that power Fortune 500 companies. Multi-billion dollar implementations. Enterprise platforms that generate revenue at scale.
            </p>
            <p>
              We saw what actually works. Not the marketing promises—the real architectures, the proven methodologies, the systems that generate billions in value.
            </p>
            <p>
              And we saw the artificial barrier keeping these capabilities out of reach for the 43% of GDP generated by small and medium businesses.
            </p>
          </div>
        </div>
      </Section>

      <Section background="medium">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-4xl font-bold mb-8">The Problem We Saw</h2>

          <div className="grid md:grid-cols-2 gap-6">
            <Card>
              <h3 className="text-2xl font-semibold mb-4">Enterprise Reality</h3>
              <ul className="space-y-3 text-gray-300">
                <li>• Systems that generate billions in revenue</li>
                <li>• Proven methodologies with documented ROI</li>
                <li>• Full transparency into how everything works</li>
                <li>• Complete control and ownership</li>
              </ul>
            </Card>

            <Card>
              <h3 className="text-2xl font-semibold mb-4">SMB Reality</h3>
              <ul className="space-y-3 text-gray-300">
                <li>• Black-box SaaS tools they rent but don&apos;t own</li>
                <li>• Promises without proof or context</li>
                <li>• Vendor lock-in and mounting costs</li>
                <li>• No access to enterprise-grade intelligence</li>
              </ul>
            </Card>
          </div>
        </div>
      </Section>

      <Section background="dark">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-4xl font-bold mb-8">Why We Built ClearForge</h2>

          <div className="space-y-6 text-lg text-gray-300">
            <p>
              The technology gap isn&apos;t about capability—it&apos;s about access. Small businesses don&apos;t need different technology. They need the same intelligence-driven systems that power enterprises, without the enterprise complexity and cost.
            </p>
            <p>
              We built <strong className="text-white">The Foundry</strong> as the AI engine that removes the artificial barriers. Same enterprise-grade intelligence. Same proven methodologies. Accessible pricing and transparent operation.
            </p>
            <p>
              We validate everything through <strong className="text-white">The Continuum</strong>—12-18 month partnerships that prove methodologies work before we ever launch commercially. Not promises. Proof.
            </p>
            <p>
              And we share everything through <strong className="text-white">The Forge</strong>—free education, resources, and community. Because gatekeeping serves vendors, not customers.
            </p>
          </div>
        </div>
      </Section>

      <Section background="gradient">
        <div className="max-w-3xl mx-auto text-center">
          <h2 className="text-3xl font-bold mb-6">
            Join Us
          </h2>
          <p className="text-xl text-gray-300 mb-8">
            We&apos;re building a better way. Transparent. Accessible. Proven.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button href="/about/mission" size="lg">
              Read Our Mission
            </Button>
            <Button href="/contact?type=beta-os" variant="outline" size="lg">
              Join Beta Program
            </Button>
          </div>
        </div>
      </Section>
    </>
  );
}
